### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ElectronMiku** [UtaUtaUtau/VPR-Real-Voice#1]
getting this error when drag and dropping:
```
08/03/23 Thu 01:46:25: Reading label
Traceback (most recent call last):
  File "vpr_rv.py", line 165, in <module>
    lab.append(LabelLine.from_line(l, isHTK))
  File "vpr_rv.py", line 50, in from_line
    return LabelLine(float(spl[0]), float(spl[1]), spl[2], isHTK)
IndexError: list index out of range
```
this is what my text file contains:
```
0.371371	0.371371	bh
0.487424	0.487424	e
0.566613	0.566613	tS
0.600747	0.600747	e
0.749568	0.749568	z
5.907797	5.907797	
```

**Comment by UtaUtaUtau** [comment]
you have an empty label... you should add `Sil` if there's silence in the label, they won't be added in as notes

**Comment by ElectronMiku** [comment]
worked, thanks!
(btw, u dont actually have to put "Sil" in there, anything that vocaloid doesnt recognize as a phoneme works 👍🏼 )
